# Form implementation generated from reading ui file 'tianditu_apikey_management_widget_qt_designer.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(448, 113)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonUpdateKey = QtWidgets.QPushButton(parent=Form)
        self.pushButtonUpdateKey.setObjectName("pushButtonUpdateKey")
        self.gridLayout.addWidget(self.pushButtonUpdateKey, 1, 1, 1, 1)
        self.lineEditKey = QtWidgets.QLineEdit(parent=Form)
        self.lineEditKey.setObjectName("lineEditKey")
        self.gridLayout.addWidget(self.lineEditKey, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)

        self.retranslateUi(Form)
        self.pushButtonUpdateKey.clicked.connect(Form.pushButtonUpdateKeyClicked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "天地图API秘钥管理"))
        self.pushButtonUpdateKey.setText(_translate("Form", "更新Key（将重启应用）"))
        self.label.setText(_translate("Form", "本应用使用天地图(www.tianditu.gov.cn)提供地理化信息服务，该服务需要注册API秘钥，请登陆网站->开发资源->地图API->申请Key，并将申请到的API秘钥填写至下方："))
